version: '3.9'

services:
  frontend:
    build:
      context: organaizer
      target: development
    image: supercalendar/frontend
    container_name: SuperCalendarFrontend
    depends_on:
      - backend
    ports:
      - "3000:3000"
    volumes:
      - ./organaizer/src:/code/src:ro
    networks:
      - client-side
    environment:
      - API_PATH=http://backend:8080/

  backend:
    build: backend
    image: supercalendar/backend
    container_name: SuperCalendarBackend
    ports:
      - "8080:8080"
    depends_on:
      db:
        condition: service_healthy
    volumes:
      - ./backend/app:/code/app:ro
    environment:
      - SQLALCHEMY_DATABASE_URL=postgresql://postgres:password@db/calendar
    networks:
      - client-side
      - server-side

  db:
    image: postgres:14
    container_name: SuperCalendarDB
    restart: always
    shm_size: 128mb
    ports:
      - "5432:5432"
    environment:
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: password
      POSTGRES_DB: calendar
    networks:
      - server-side
    healthcheck:
      test: [ "CMD-SHELL", "pg_isready -U postgres" ]
      interval: 5s
      timeout: 5s
      retries: 5

#    volumes:
#      - ./postgresql/data:/var/lib/postgresql/data

networks:
  client-side: { }
  server-side: { }